### PR TITLE
PyPDF4/filters.py unit tests

### PR DESCRIPTION
**Pull request by newnone**
This is an ongoing PR - **do not close it** right after the first merge, I will continue pushing more until I say I am done with it. In the meantime, review and eventually merge the existng code.

I have continued adding unit tests for filters in `PyPDF4/filters.py`, and admittedly they turned out quite useful in estirpating a few bugs or refactoring some algorithms. As of now, I'm not fully sure that `LZWDecode.Decoder` is bug-free as I found it in the codebase prior to working on it; indeed, one of its test cases keeps failing.

There were also a few other commits not fully related to unit testing, but they were good enough to be added.

### CODE REVIEW

**Comment by newnone** [comment]
This should end issue #8. There's only one `staticmethod()` direct call but it is not proper to modify.

**Comment by newnone** [comment]
[Commit 169dce1](https://github.com/claird/PyPDF4/pull/9/commits/169dce150c8a42fc67f27c5ae3049c030c0683c6) should end issue #8. There's only one `staticmethod()` direct call but it is not proper to modify.

**Comment by newnone** [comment]
Hey @claird, isn't it possible to set Pylint flags such as these in the source code:
```
class CCITTFaxDecode(object):    # pylint: disable=too-few-public-methods
    @staticmethod
```

in the configuration of the Pylint tool? I will check myself, and if you agree will weed out those invasive comment declarations.

**Comment by claird** [comment]
Pylint indeed respects a .pylintrc.

As I understand .pylintrc, if I mention too-few-public-methods there, it
will turn off that check for *all* methods.  I want to leave the checks on
for at least a while longer.  I understand your point that static methods
don't deserve the stigma of a source #pylint declaration.  While I suspect
there's a good solution for that issue, I haven't researched it yet.

Cameron Laird, vice president
We make computers work for people.

**Comment by newnone** [comment]
I had been prolonging `Add fixes to Sample_Code/*.py.` for too long, and I decided to include it in this PR even if not intimately related. (It is a very small modification to an unessential part of the project.)

**Comment by newnone** [comment]
>This is an ongoing PR - do not close it right after the first merge

I am noting that GitHub doesn't allow reopening PRs that were just merged. Will need to find a workaround or just resort to opening a new one each time.

**Comment by newnone** [comment]
Hey @claird, since PRs cannot be reused on GitHub you can merge the changes in #9 and close it.

**Comment by claird** [comment]
Thank you, newnone, for your contributions and patience.

**Pull request merged**
